# Generated by Django 2.2 on 2021-05-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapmanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posisipohon',
            name='kmz',
        ),
        migrations.AddField(
            model_name='posisipohon',
            name='urlmap',
            field=models.URLField(default='', max_length=500),
        ),
    ]
