# Generated by Django 2.2 on 2021-05-12 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapmanager', '0002_auto_20210512_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posisipohon',
            name='relasi',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='urlrelasi', to=settings.AUTH_USER_MODEL),
        ),
    ]
