# Generated by Django 2.2 on 2021-04-10 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landing_page',
            old_name='visi_misi',
            new_name='visi_misi_and_core_value',
        ),
    ]
