# Generated by Django 2.2 on 2021-04-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_auto_20210410_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing_page',
            name='image_1',
            field=models.ImageField(default='', upload_to='landing_page_image'),
        ),
        migrations.AddField(
            model_name='landing_page',
            name='image_2',
            field=models.ImageField(default='', upload_to='landing_page_image'),
        ),
        migrations.AddField(
            model_name='landing_page',
            name='image_3',
            field=models.ImageField(default='', upload_to='landing_page_image'),
        ),
    ]
