# Generated by Django 2.2 on 2021-04-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_auto_20210410_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing_page',
            name='name',
            field=models.CharField(default='Edit Landing Page', max_length=20),
        ),
    ]
