# Generated by Django 2.2 on 2021-04-10 07:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0005_auto_20210410_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landing_page',
            options={'verbose_name_plural': 'Landing Page'},
        ),
        migrations.AlterField(
            model_name='landing_page',
            name='history',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
