# Generated by Django 2.2 on 2021-05-25 19:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0009_auto_20210410_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=255)),
                ('user_occupation', models.CharField(default='', max_length=255)),
                ('user_review', ckeditor.fields.RichTextField()),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='landingpage.Landing_page')),
            ],
            options={
                'verbose_name_plural': 'User Review',
            },
        ),
        migrations.CreateModel(
            name='Management_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(default='', max_length=255)),
                ('staff_position', models.CharField(default='', max_length=255)),
                ('staff_photo', models.ImageField(default='None', upload_to='staff_photos')),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='landingpage.Landing_page')),
            ],
            options={
                'verbose_name_plural': 'BOARD & MANAGEMENT TEAM',
            },
        ),
    ]
