# Generated by Django 2.2 on 2021-05-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0010_management_team_user_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management_team',
            name='staff_photo',
            field=models.ImageField(default='default.png', upload_to='staff_photos'),
        ),
    ]
