# Generated by Django 2.2 on 2021-05-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0011_auto_20210526_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management_team',
            name='staff_photo',
            field=models.ImageField(default='staff_photos/default.png', upload_to='staff_photos'),
        ),
    ]
