# Generated by Django 2.2 on 2021-05-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0013_auto_20210526_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management_team',
            name='staff_social_facebook',
            field=models.URLField(default='#', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='management_team',
            name='staff_social_instagram',
            field=models.URLField(default='#', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='management_team',
            name='staff_social_linkedin',
            field=models.URLField(default='#', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='management_team',
            name='staff_social_twitter',
            field=models.URLField(default='#', max_length=1000, null=True),
        ),
    ]
