# Generated by Django 2.2 on 2021-05-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0015_auto_20210526_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing_page',
            name='office_address',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='landing_page',
            name='office_email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='landing_page',
            name='office_location_map',
            field=models.CharField(default='#', max_length=1000),
        ),
        migrations.AddField(
            model_name='landing_page',
            name='office_phone_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
