# Generated by Django 2.2 on 2021-06-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0017_faq_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
