# Generated by Django 2.2 on 2021-06-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0018_faq_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_answer',
            name='post',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
