# Generated by Django 2.2 on 2021-06-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0019_auto_20210605_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_answer',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
