# Generated by Django 2.2 on 2021-08-09 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0021_auto_20210605_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landing_page',
            old_name='image_1',
            new_name='history_image',
        ),
        migrations.RenameField(
            model_name='landing_page',
            old_name='image_2',
            new_name='strategy_and_program_image',
        ),
        migrations.RenameField(
            model_name='landing_page',
            old_name='image_3',
            new_name='visi_misi_image',
        ),
    ]
