# Generated by Django 2.2 on 2021-09-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0022_auto_20210809_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing_page',
            name='no_rek',
            field=models.CharField(default='', max_length=100),
        ),
    ]
