# Generated by Django 2.2 on 2021-05-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login_page',
            options={'verbose_name_plural': 'Login Page Demo'},
        ),
    ]
