# Generated by Django 2.2 on 2021-05-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210501_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_page',
            name='name',
            field=models.CharField(default='Edit Login Page Demo', max_length=20),
        ),
    ]
