# Generated by Django 2.2 on 2021-08-10 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20210810_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='profile_image',
        ),
    ]
