# Generated by Django 2.2 on 2021-09-05 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_posisipohon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posisipohon',
        ),
    ]
