# Generated by Django 2.2 on 2021-09-05 09:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(default='', max_length=255)),
                ('sponsor_logo', models.ImageField(blank=True, default='staff_photos/default.png', null=True, upload_to='sponsor_logo')),
                ('sponsor_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sponsors',
            },
        ),
        migrations.CreateModel(
            name='Sponsor_galery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2020, 10, 18))),
                ('images', models.ImageField(upload_to='_image')),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sponsor_dashboard.User_sponsor')),
            ],
        ),
    ]
