# Generated by Django 2.2 on 2021-06-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_sponsor',
            options={'verbose_name_plural': 'Sponsors'},
        ),
        migrations.AlterField(
            model_name='sponsor_galery',
            name='images',
            field=models.ImageField(upload_to='_image'),
        ),
    ]
