# Generated by Django 2.2 on 2021-09-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_sponsor',
            old_name='sponsor_user',
            new_name='sponsor_user',
        ),
    ]
