# Generated by Django 2.2 on 2021-06-06 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_dashboard', '0003_auto_20210606_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_sponsor',
            name='sponsor_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
