# Generated by Django 2.2 on 2021-04-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program_activity',
            options={'verbose_name_plural': 'Program Activity'},
        ),
        migrations.RemoveField(
            model_name='program_activity',
            name='image',
        ),
        migrations.AlterField(
            model_name='program_activity',
            name='category',
            field=models.CharField(choices=[('On Going', 'On Going'), ('Latest Project', 'Latest Project'), ('Kedai Hutan Cempaka', 'Kedai Hutan Cempaka'), ('Cempaka Adventure', 'Cempaka Adventure')], max_length=20, verbose_name='Kategori'),
        ),
    ]
