# Generated by Django 2.2 on 2021-06-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program_activity',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='meta_description'),
        ),
    ]
