# Generated by Django 2.2 on 2021-05-02 07:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program_activity', '0003_program_activity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_activity',
            name='meta_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='meta_description'),
        ),
    ]
