# Generated by Django 2.2 on 2021-05-01 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_article',
            options={'verbose_name_plural': 'Add Article/News'},
        ),
    ]
