# Generated by Django 2.2 on 2021-05-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210502_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_article',
            name='banner',
            field=models.ImageField(default='', upload_to='article_images'),
        ),
    ]
