# Generated by Django 2.2 on 2021-12-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posisipohon',
            name='year',
            field=models.IntegerField(default=2020),
        ),
        migrations.AddConstraint(
            model_name='posisipohon',
            constraint=models.UniqueConstraint(fields=('relations', 'year'), name='unique map per year'),
        ),
    ]
