# Generated by Django 2.2 on 2021-12-26 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps_manager', '0002_auto_20211226_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posisipohon',
            name='relations',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='urlrelasi', to=settings.AUTH_USER_MODEL),
        ),
    ]
